### PR TITLE
Unify paths

### PR DESCRIPTION
**Pull request by stokbaek**
@stealthpyro can you test and see if this path system also works in Windows before I make a merg. Should also work with version in Windows with this code

### CODE REVIEW

**Comment by NickMariano** [comment]
Instructions should include:
 C:\opt\simc-discord is where the directory needs to live on windows.
Simcraft needs to be located here: C:\usr\local\sbin\simc

I also had to change this line to include simc.exe - I'm not familar with python so I'm not sure how else you can handle having to call the actual exe. There also needs to be a space after it like below.

 os.system(os.path.join('/usr', 'local', 'sbin', 'simc', 'simc.exe ' + options + ' > ' + htmldir + 'debug',
                           'simc.stout 2> ' + htmldir + 'debug', 'simc.sterr &'))

**Comment by stokbaek** [comment]
I made it so you have to give it the full path for simc executable in user_data.json. It should not be needed to change anything in simc.py now.

Can you once again test if it works on Windows?

**Comment by NickMariano** [comment]
Everything appears to be working without any changes to the simc.py file. 

Just want to clarify that the actual simulations from armory or addon are working. Reading the help file and checking version do not work.

**Comment by NickMariano** [comment]
When checking version:

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "simc.py", line 86, in on_message
    await bot.send_message(message.channel, *version[:1])
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild
_id, tts=tts, embed=embed)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an emp
ty message


When checking help file:

 Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "simc.py", line 83, in on_message
    msg = open('help.file', 'r').read()
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp
1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 390: char
acter maps to <undefined>

**Comment by stokbaek** [comment]
Tested on a virtual machine. All should work in Windows now. Due note that some changes needs to be done to the executable section for windows in the `user_data.json`
Windows example:
`"executable": "START /B C:\\Simulationcraft^(x64^)\\710-03\\simc.exe",`
* `START` makes it run in the background, this is needed to get the update icon rotating in discord
* `/B` allows output to be written to file
* `^` is windows way to escape a character. If `( ) ` is not escaped will it fail because it cannot find path

**Pull request merged**
